version: "3.9"

services:

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: employee_db
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - three-tier-network

  backend:
    build: ./backend
    container_name: flask-container
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - three-tier-network

  frontend:
    build: ./frontend
    container_name: nginx-container
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - three-tier-network

volumes:
  mysql-data:

networks:
  three-tier-network:
